#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# frontend lint
cd frontend && npm run lint || exit 1
npm run build || exit 1

# backend lint
cd ../backend || exit 1
bundle exec rubocop -A || exit 1

cd .. || exit 1
git add .
