name: Deploy to Lightsail on PR Merge

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Lightsail
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install SSH client
        run: sudo apt-get update && sudo apt-get install -y openssh-client

      - name: Deploy via SSH to Lightsail
        env:
          LIGHTSAIL_SSH_KEY: ${{ secrets.LIGHTSAIL_SSH_KEY }}
          LIGHTSAIL_HOST: ${{ secrets.LIGHTSAIL_HOST }}
          LIGHTSAIL_USER: ${{ secrets.LIGHTSAIL_USER }}
        run: |
          mkdir -p ~/.ssh
          echo "${LIGHTSAIL_SSH_KEY}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh -o StrictHostKeyChecking=no ${LIGHTSAIL_USER}@${LIGHTSAIL_HOST} << 'EOF'
            # ここに Lightsail で実行したいデプロイコマンドを記述してください
            cd /home/ec2-user/exit_cheat_bs
            git pull origin main
            docker-compose down
            ENV=production docker-compose -f docker-compose.yml up -d --build
          EOF
